### PR TITLE
feature-complete draft

### PR DESCRIPTION
**Pull request by zmitton**
@meowsbits @tzdybal

Could you guys give me any tips on (mostly) the code _orginization_ of this project. Its the first thing I've written in golang (really like the concurrency model!). The structure of packages was very complex and confusing to me. 

Also any tips for integrating this with go-ethereum? where would these files be placed?

### CODE REVIEW

**Comment by zmitton** [comment]
the filestructure can be found [here](https://github.com/zmitton/go-merklemountainrange/tree/draft) (might be easier to navigate than looking at diffs)

**Comment by meowsbits** [comment]
This looks about right to me. It looks like you're organizing around logical spaces. In general, I try to make packages keeping in mind that _packages are for importing_, so I try to keep the stuff in them making sense from a 'Would this make sense to import and use somewhere else?' perspective (which then applies to your project first). 

Using a package like '/mmr' in a project that is also essentially named 'mmr' is also following an idiom. Usually these packages are 'app-specific essential logic' that ties together the more bare bones logic from the adjacent surrounding packages to yield the meat of the project. For CLI apps this package is then imported by a '/cmd' package which will handle exposing that logic to a CLI API.

**Comment by zmitton** [comment]
thanks for the tips. I took a little break, but everything is working and tested now on master. Actually @tzdybal if you don't mind looking at [this](https://github.com/zmitton/go-merklemountainrange/blob/master/db/filebaseddb.go#L113) I took your advice about syncing the db file, but it makes the persistent `append` operation nearly 1000x slower than everything else. Only 2.5ms but still:

```
memoryBased GetUnverified:           800ns
memoryBased Get:                   3.8µs
memoryBased Append:                6.0µs

fileBased GetUnverified:           2.0µs
fileBased Get:                    38.9µs
fileBased Append               2.5ms
```

**Comment by zmitton** [comment]
I know its the `fs.sync()` because when I take it away, everything flys

**Pull request closed without merging**
